name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: 2.0.0
      - run: nimble install -y
      - run: nimble test
